// Mapper le nom du produit à son image
export const getProductImage = (productName: string): string | null => {
  const imageMap: Record<string, string> = {
    'Ail frais': '/products/fresh_garlic.avif',
    'Ananas': '/products/pineapple.avif',
    'Asperges': '/products/asparagus.avif',
    'Avocat': '/products/avocado.avif',
    'Bacon': '/products/bacon.png',
    'Baguette': '/products/bread.avif',
    'Bœuf haché': '/products/ground-beef.avif',
    'Basilic frais': '/products/fresh-basil.avif',
    'Beurre': '/products/butter.avif',
    'Bière blonde': '/products/blond_beer.avif',
    'Brocoli': '/products/broccoli.avif',
    'Bâtonnets de poisson surgelés': '/products/frozen-fish-sticks.avif',
    'Café en grains': '/products/coffee_beans.avif',
    'Chapelure assaisonnée': '/products/seasoned_breadcrumbs.avif',
    'Citrons': '/products/lemons.avif',
    'Coriandre fraîche': '/products/fresh-cilantro.avif',
    'Carottes': '/products/carotts.avif',
    'Cheddar': '/products/cheddar.avif',
    'Coca-Cola': '/products/coca-cola.avif',
    'Concombre': '/products/cucumber.avif',
    'Cornichons': '/products/pickles.avif',
    'Crème 35%': '/products/cream35.avif',
    'Crème glacée vanille': '/products/vanilla-ice-cream.avif',
    'Croquettes de poulet surgelées': '/products/frozen-chicken-nuggets.avif',
    'Farine tout usage': '/products/all-purpose-flour.avif',
    'Frites surgelées': '/products/frozen-fries.avif',
    'Fruits rouges surgelés': '/products/frozen-berries.avif',
    'Haricots verts surgelés': '/products/frozen-green-beans.avif',
    "Huile d'olive": '/products/olive-oil.avif',
    'Huile végétale': '/products/vegetable-oil.avif',
    "Jus d'orange": '/products/orange-juice.avif',
    'Ketchup': '/products/ketchup.avif',
    'Lait 3.25%': '/products/milk325.avif',
    'Laitue romaine': '/products/romaine-lettuce.avif',
    'Limes': '/products/limes.avif',
    'Légumes mélangés surgelés': '/products/frozen-mixed-vegetables.avif',
    'Maïs en grains surgelé': '/products/frozen-corn-kernels.avif',
    'Marinade pour poulet': '/products/chicken-marinade.avif',
    'Mayonnaise': '/products/mayonnaise.avif',
    'Mélange d\'épices maison': '/products/house-spice-blend.avif',
    'Moutarde': '/products/mustard.avif',
    'Oignons jaunes': '/products/yellow-onions.avif',
    'Pain à burger': '/products/burger-bun.avif',
    'Parmesan': '/products/parmesan.avif',
    'Poivre noir': '/products/black-pepper.avif',
    'Pâte feuilletée surgelée': '/products/frozen-puff-pastry.avif',
    'Pâtes sèches': '/products/dry-pasta.avif',
    'Pizza surgelée': '/products/frozen-pizza.avif',
    'Poitrine de poulet': '/products/chicken-breast.avif',
    'Poivrons rouges': '/products/red-bell-pepper.avif',
    'Pois verts surgelés': '/products/frozen-green-peas.avif',
    'Pommes de terre': '/products/potatoes.avif',
    'Rhum blanc': '/products/white-rum.avif',
    'Riz blanc': '/products/white-rice.avif',
    'Sel': '/products/salt.avif',
    "Sirop d'érable": '/products/maple-syrup.avif',
    'Sorbet aux fruits': '/products/fruit-sorbet.avif',
    'Sucre blanc': '/products/white-sugar.avif',
    'Thon en conserve': '/products/canned-tuna.png',
    'Tortillas': '/products/tortillas.avif',
    'Vinaigre balsamique': '/products/balsamic-vinegar.avif',
    'Vin blanc': '/products/white-wine.avif',
    'Vin rouge': '/products/red-wine.avif',
    'Œufs': '/products/eggs.avif',
    'Épinards surgelés': '/products/frozen-spinach.avif',
  };
  const result = imageMap[productName] || null;
  if (!result) {
    console.warn('⚠️ No image found for product:', productName);
  }
  return result;
};
